doc_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('managers.urls')),
    path('admin/', admin.site.urls),
]

managers/urls.py
from django.urls import path, re_path
from .views import clients, requests, documents, client_view_doc, client_view, request_view, choose_request, client_auth, client_pin, doc_form, show_file, client_view_request

urlpatterns = [
    # Links for RM facing interface
    re_path(r'^client/$', client_view, name="client_view"),
    re_path(r'^client/request/$', client_view_request,
            name="client_view_request"),
    re_path(r'^client/document/$', client_view_doc,
            name="client_view_doc"),
    re_path(r'^request/(?P<request_id>\d+)/$', request_view,
            name="request_view"),
    re_path(r'^choose_request/$', choose_request, name="choose_request"),

    path('', clients, name="clients"),
    path('requests', requests, name="requests"),
    path('documents', documents, name="documents"),

    # this represents the view that handles downloading or viewing of files
    re_path(r'^managers/files/$', show_file, name='show_file'),

    # Links for Client facing interface
    path('client_auth', client_auth, name="client_auth"),
    path('client_pin', client_pin, name="client_pin"),
    path('doc_form', doc_form, name='doc_form'),
]

managers/models.py
from django.db import models


class Client(models.Model):
    """ # ? top level client model """
    name = models.CharField(max_length=50, blank=False, null=False)
    surname = models.CharField(max_length=50, blank=False, null=False)
    email = models.EmailField(
        max_length=50, blank=True, null=True, unique=True)

    def __str__(self):
        return str(self.id)


class Request(models.Model):
    """ #? second level requests associated with client """
    name = models.CharField(max_length=50, blank=False, null=False)
    submitted = models.BooleanField(default=False, blank=False)
    date_submitted = models.DateTimeField(auto_created=True, blank=False)
    client = models.ForeignKey(
        Client, on_delete=models.CASCADE, related_name='requests')

    def __str__(self):
        return str(self.id)


class Document(models.Model):
    """ #? second level documents associate with client and request """
    name = models.CharField(max_length=50, blank=False, null=False)
    date = models.DateTimeField(auto_created=True, blank=False)
    document = models.FileField(
        upload_to='./managers/files', blank=False, null=False)
    request = models.ForeignKey(
        Request, on_delete=models.CASCADE, default=1, related_name='documents')
    client = models.ForeignKey(
        Client, on_delete=models.CASCADE, related_name='documents')

    def __str__(self):
        return str(self.id)

templates/client_portal/client_auth.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Include the Bulma CSS framework for styling -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css" />
    <title>Client Login</title>
  </head>
  <body >
    <div class="columns is-centered is-full" style={{"height:150px"}}></div>
    <div class="columns is-centered is-full">
      <div class="block is-full">
        <div class="box">
          <p class="subtitle is-4">In order to submit the documents please enter your email address. <br> You will be given one time pin to enter.</p>
          <form action="{% url 'client_auth' %}" method="POST">
            {% csrf_token %}
          <div class="field">
            <label class="label">Email</label>
            <div class="control">
              <input class="input" type="email" placeholder="Email input" name="email" value="" />
            </div>
          </div>

          <div class="field">
            <div class="control">
              <label class="checkbox">
                <input type="checkbox" />
                I agree to the <a href="#">terms and conditions</a>
              </label>
            </div>
          </div>

          <div class="field is-grouped">
            <div class="control">
              <button class="button is-link">Submit</button>
            </div>
            <div class="control">
              <button disabled="true" class="button is-link is-light">Cancel</button>
            </div>
          </div>
        </form>
        </div>
      </div>
    </div>
  </body>
  <script>
    document.addEventListener("DOMContentLoaded", () => {
      // Functions to open and close a modal
      function openModal($el) {
        $el.classList.add("is-active");
      }

      function closeModal($el) {
        $el.classList.remove("is-active");
      }

      function closeAllModals() {
        (document.querySelectorAll(".modal") || []).forEach(($modal) => {
          closeModal($modal);
        });
      }

      // Add a click event on buttons to open a specific modal
      (document.querySelectorAll(".js-modal-trigger") || []).forEach(($trigger) => {
        const modal = $trigger.dataset.target;

        const $target = document.getElementById(modal);

        $trigger.addEventListener("click", () => {
          openModal($target);
        });
      });

      // Add a click event on various child elements to close the parent modal
      (document.querySelectorAll(".modal-background, .modal-close, .modal-card-head .delete, .modal-card-foot .button") || []).forEach(($close) => {
        const $target = $close.closest(".modal");

        $close.addEventListener("click", () => {
          closeModal($target);
        });
      });

      // Add a keyboard event to close all modals
      document.addEventListener("keydown", (event) => {
        const e = event || window.event;

        if (e.keyCode === 27) {
          // Escape key
          closeAllModals();
        }
      });
    });
  </script>
  <script>
    function searchFunction() {
      var input, filter, table, tr, td, i, txtValue;
      input = document.getElementById("searchInput");
      filter = input.value.toUpperCase();
      table = document.getElementById("list_Table");
      tr = table.getElementsByTagName("tr");
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[0];
        if (td) {
          txtValue = td.textContent || td.innerText;
          if (txtValue.toUpperCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }
      }
    }
  </script>
</html>

templates/client_portal/client_pin.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Include the Bulma CSS framework for styling -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css" />
    <title>Client Login</title>
  </head>
  <body >
    <div class="columns is-centered is-full" style={{"height:150px"}}></div>
    <div class="columns is-centered is-full">
      <div class="block is-full">
        <div class="box">
          <p class="subtitle is-4">Please enter your one time pin that was sent to your email address.</p>

          <div class="field">
            <label class="label">One time Pin</label>
            <div class="control">
              <form action="{% url 'client_pin' %}" method="POST">
                {% csrf_token %}
              <input class="input" type="password" placeholder="One Time Pin" name="pin" value="" />

            </div>
          </div>

          <div class="field is-grouped">
            <div class="control">
              <button class="button is-link" name="client_id" value={{client_id}}>Submit</button>
            </div>
          </div>
        </form>
        </div>
      </div>
    </div>
  </body>
  <script>
    document.addEventListener("DOMContentLoaded", () => {
      // Functions to open and close a modal
      function openModal($el) {
        $el.classList.add("is-active");
      }

      function closeModal($el) {
        $el.classList.remove("is-active");
      }

      function closeAllModals() {
        (document.querySelectorAll(".modal") || []).forEach(($modal) => {
          closeModal($modal);
        });
      }

      // Add a click event on buttons to open a specific modal
      (document.querySelectorAll(".js-modal-trigger") || []).forEach(($trigger) => {
        const modal = $trigger.dataset.target;

        const $target = document.getElementById(modal);

        $trigger.addEventListener("click", () => {
          openModal($target);
        });
      });

      // Add a click event on various child elements to close the parent modal
      (document.querySelectorAll(".modal-background, .modal-close, .modal-card-head .delete, .modal-card-foot .button") || []).forEach(($close) => {
        const $target = $close.closest(".modal");

        $close.addEventListener("click", () => {
          closeModal($target);
        });
      });

      // Add a keyboard event to close all modals
      document.addEventListener("keydown", (event) => {
        const e = event || window.event;

        if (e.keyCode === 27) {
          // Escape key
          closeAllModals();
        }
      });
    });
  </script>
  <script>
    function searchFunction() {
      var input, filter, table, tr, td, i, txtValue;
      input = document.getElementById("searchInput");
      filter = input.value.toUpperCase();
      table = document.getElementById("list_Table");
      tr = table.getElementsByTagName("tr");
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[0];
        if (td) {
          txtValue = td.textContent || td.innerText;
          if (txtValue.toUpperCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }
      }
    }
  </script>
</html>

templates/client_portal/doc_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Include the Bulma CSS framework for styling -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css" />
    <title>Client Dashboard</title>
  </head>
  <body>
    <section class="hero is-small is-success mb-4">
      <div class="hero-body columns">
        <div class="column iis-three-quarters is-vcentered">
          <h1 class="title is-4">Documents Upload</h1>
          <p class="subtitle is-6">This page allows you to upload all the documents for the request specified by your RM.</p>
        </div>
        <form method="GET" action="{% url 'client_auth' %}">
          {% csrf_token %}
          <div class="column is-vcentered is-right">
            <button class="button small is-dark">Exit</button>
          </div>
        </form>
      </div>
    </section>

    <div class="block">
      <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth" id="list_Table">
        <thead>
          <tr>
            <th>Request Name</th>
            <th>Documents Submitted</th>
            <th>Action</th>
            <th>Submit</th>
          </tr>
        </thead>
        <tbody>
          {% for request in requests%}
          <tr>
            <form method="POST" class="post-form" action="{% url 'doc_form' %}" enctype="multipart/form-data">
              {% csrf_token %} {% comment %} <input id="id_document" name="document" type="file" /> {% endcomment %}
              <td>{{request.name}}</td>
              <td>
                {% if request.submitted%}
                <button class="button is-success">
                  <span class="icon is-small"> True </span>
                </button>
                {%else %}
                <button class="button is-warning">
                  <span class="icon is-small"> False </span>
                </button>
                {% endif %}
              </td>
              <td>
                <div>{{ form.as_p }}</div>
              </td>
              <td>
                <input hidden="true" id="id_document" name="client_id" value="{{client_id}}" type="text" />
                <div class="column is-vcentered is-right">
                  <button class="button small is-dark" name="request_id" value="{{request.id}}">Submit Document</button>
                </div>
              </td>
            </form>
          </tr>
          {% endfor%}
        </tbody>
      </table>
      <div />
    </div>
  </body>
  <script>
    document.addEventListener("DOMContentLoaded", () => {
      // Functions to open and close a modal
      function openModal($el) {
        $el.classList.add("is-active");
      }

      function closeModal($el) {
        $el.classList.remove("is-active");
      }

      function closeAllModals() {
        (document.querySelectorAll(".modal") || []).forEach(($modal) => {
          closeModal($modal);
        });
      }

      // Add a click event on buttons to open a specific modal
      (document.querySelectorAll(".js-modal-trigger") || []).forEach(($trigger) => {
        const modal = $trigger.dataset.target;

        const $target = document.getElementById(modal);

        $trigger.addEventListener("click", () => {
          openModal($target);
        });
      });

      // Add a click event on various child elements to close the parent modal
      (document.querySelectorAll(".modal-background, .modal-close, .modal-card-head .delete, .modal-card-foot .button") || []).forEach(($close) => {
        const $target = $close.closest(".modal");

        $close.addEventListener("click", () => {
          closeModal($target);
        });
      });

      // Add a keyboard event to close all modals
      document.addEventListener("keydown", (event) => {
        const e = event || window.event;

        if (e.keyCode === 27) {
          // Escape key
          closeAllModals();
        }
      });
    });
  </script>
</html>